name: s3-ec2-infra-init-plan

on:
  push:
    branch: "infra"
  pull_request:
    branch: "infra"

jobs:
  terraformEC2:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash

    outputs:
      public_ip: ${{steps.ip_address.outputs.ip}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Terraform Init
        run: |
          cd Terraform
          cd ec2
          terraform init
      - name: Terraform Plan
        run: |
          cd Terraform
          cd ec2
          terraform plan
